[#7] Clean osolete environments
aposin/gem pull request #12
Opened 2021-09-01 07:21 UTC by siniann

## Type of request

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Refactoring 
- [ ] Documentation or documentation changes

## Related Issue(s)

## Concept 

#### Description of the change
Clean obsolete worktrees 

#### Description of current state
Functionlity to Clean obsolete worktrees is not available
#### Description of target state
Add a menu item to provide the clean up functionality. Allow the user to choose the obsolete worktrees to delete.
#### Estimated investment / approximate investment

#### Initiator
name / company / position / created at

## Technical information
#### Platform / target area

#### known side-effects

#### other 

#### How has this Tested?

#### Screenshots, Uploads, other documents (if appropriate):

## Checklist:

- [x] All the commits are signed.
- [x] My code follows the code style of this project.
- [x] I agree with die CLA.
- [x] I have read the CONTRIBUTING docs.
- [x] I have added/updated necessary documentation (if appropriate).

2021-09-01 07:21 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/aposin/gem?pullRequest=12) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/aposin/gem?pullRequest=12) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/aposin/gem?pullRequest=12) it.</sub>

2021-09-07 12:13 UTC, d-gs requested changes
Thanks a lot for your work. It looks like we can refine the workflow for the end-user a bit, avoiding to inform when nothing is selected by:

* Do not allow to cancel the fetch of the obsolete environments
* Disabling the OK button and not doing anything while closing and/or cancel on the dialog
* Inform the user if some worktree launcher cannot be launch (meaning that the obsolete environment cannot be removed)
* Showing before start the deletion the list of environments to be removed

The other comments are to cleanup, reduce the information for the end-user about internal concepts and i18n improvements.

Back to you @siniann!

2021-09-07 12:13 UTC, d-gs commented on bundles/org.aposin.gem.ui/src/org/aposin/gem/ui/dialog/progress/internal/ObsoleteEnvironmentDialog.java
> +
Nitpicking comment: extra new-line.

2021-09-07 12:13 UTC, d-gs commented on bundles/org.aposin.gem.ui/src/org/aposin/gem/ui/message/messages.properties
> +branch.label = Branch
Actually the branch one is not necessary if the column is removed.

2021-09-08 15:04 UTC, d-gs reviewed
I leave some comments for tomorrow. @davu-all will take over the review

2021-09-08 15:04 UTC, d-gs commented on bundles/org.aposin.gem.ui/src/org/aposin/gem/ui/handler/CleanObsoleteEnvironmentsHandler.java
> +                        MessageFormat.format(messages.cleanObsoleteEnvironmentsHandler_message_confirmDeleteDialog,
If it is formatted, the second part of the variable should be `messageFormat`.

2021-09-08 15:04 UTC, d-gs commented on bundles/org.aposin.gem.ui/src/org/aposin/gem/ui/message/messages.properties
> +cleanObsoleteEnvironmentsHandler.message.fetchWorktreesProgressMonitor = Fetching obsolete work trees
Not fixed yet.

2021-09-09 07:00 UTC, davu-all commented on bundles/org.aposin.gem.ui/OSGI-INF/l10n/bundle.properties
> +menu.clean.obsoleteenvironments.label = Obsolete Environments
Done

2021-09-09 07:19 UTC, davu-all approved these changes
LGTM

2021-09-09 07:24 UTC, merged